Repository shubhanshu02/InstiComplaints-App, pull requests merged in 2020-10, with the labels that each got.

#30 created collections
  android/app/build.gradle
  lib/filed.dart
  lib/login.dart
  lib/main.dart
  lib/modals.dart
  lib/register.dart
  lib/resolved.dart
  lib/st_profile.dart
  lib/userDatabase.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest-accepted

#31 Added a Splash Screen to the application
  android/app/src/main/res/drawable/app_logo.png
  android/app/src/main/res/drawable/launch_background.xml
Labels: enhancement, hacktoberfest-accepted

#33 User Authentication and UI Corrections
  lib/feedPage.dart
  lib/login.dart
  lib/models.dart
  lib/register.dart
Labels: bug, enhancement

#35 Notification Updating and Complaint Filing.
  lib/AdminDialog.dart
  lib/ComplaintDialog.dart
  lib/ComplaintFiling.dart
  lib/Complaint_Class.dart
  lib/Compose.dart
  lib/DropDown.dart
  lib/ModeratorDialog.dart
  lib/UpdateNotification.dart
  lib/loading.dart
  lib/notifications.dart
  pubspec.lock
  pubspec.yaml
Labels: Backend

#41 Bug Fixes: Prerelease Check
  lib/feedPage.dart
  lib/login.dart
  lib/modifyModerators.dart
  lib/navigation.dart
  lib/register.dart
  pubspec.lock
  pubspec.yaml
Labels: release 1
